// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: DanubeApi.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProducerAccessMode int32

const (
	ProducerAccessMode_Shared    ProducerAccessMode = 0 // multiple producers can publish on a topic
	ProducerAccessMode_Exclusive ProducerAccessMode = 1 // exclusive access for producer
)

// Enum value maps for ProducerAccessMode.
var (
	ProducerAccessMode_name = map[int32]string{
		0: "Shared",
		1: "Exclusive",
	}
	ProducerAccessMode_value = map[string]int32{
		"Shared":    0,
		"Exclusive": 1,
	}
)

func (x ProducerAccessMode) Enum() *ProducerAccessMode {
	p := new(ProducerAccessMode)
	*p = x
	return p
}

func (x ProducerAccessMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProducerAccessMode) Descriptor() protoreflect.EnumDescriptor {
	return file_DanubeApi_proto_enumTypes[0].Descriptor()
}

func (ProducerAccessMode) Type() protoreflect.EnumType {
	return &file_DanubeApi_proto_enumTypes[0]
}

func (x ProducerAccessMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProducerAccessMode.Descriptor instead.
func (ProducerAccessMode) EnumDescriptor() ([]byte, []int) {
	return file_DanubeApi_proto_rawDescGZIP(), []int{0}
}

type DispatchStrategy int32

const (
	DispatchStrategy_NonReliable DispatchStrategy = 0
	DispatchStrategy_Reliable    DispatchStrategy = 1
)

// Enum value maps for DispatchStrategy.
var (
	DispatchStrategy_name = map[int32]string{
		0: "NonReliable",
		1: "Reliable",
	}
	DispatchStrategy_value = map[string]int32{
		"NonReliable": 0,
		"Reliable":    1,
	}
)

func (x DispatchStrategy) Enum() *DispatchStrategy {
	p := new(DispatchStrategy)
	*p = x
	return p
}

func (x DispatchStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DispatchStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_DanubeApi_proto_enumTypes[1].Descriptor()
}

func (DispatchStrategy) Type() protoreflect.EnumType {
	return &file_DanubeApi_proto_enumTypes[1]
}

func (x DispatchStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DispatchStrategy.Descriptor instead.
func (DispatchStrategy) EnumDescriptor() ([]byte, []int) {
	return file_DanubeApi_proto_rawDescGZIP(), []int{1}
}

type ConsumerRequest_SubscriptionType int32

const (
	ConsumerRequest_Exclusive ConsumerRequest_SubscriptionType = 0 // Only one consumer can subscribe to the topic at a time.
	ConsumerRequest_Shared    ConsumerRequest_SubscriptionType = 1 // Multiple consumers can subscribe to the topic concurrently.
	ConsumerRequest_Failover  ConsumerRequest_SubscriptionType = 2 // Only one consumer (the active consumer) receives messages at any given time.
)

// Enum value maps for ConsumerRequest_SubscriptionType.
var (
	ConsumerRequest_SubscriptionType_name = map[int32]string{
		0: "Exclusive",
		1: "Shared",
		2: "Failover",
	}
	ConsumerRequest_SubscriptionType_value = map[string]int32{
		"Exclusive": 0,
		"Shared":    1,
		"Failover":  2,
	}
)

func (x ConsumerRequest_SubscriptionType) Enum() *ConsumerRequest_SubscriptionType {
	p := new(ConsumerRequest_SubscriptionType)
	*p = x
	return p
}

func (x ConsumerRequest_SubscriptionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsumerRequest_SubscriptionType) Descriptor() protoreflect.EnumDescriptor {
	return file_DanubeApi_proto_enumTypes[2].Descriptor()
}

func (ConsumerRequest_SubscriptionType) Type() protoreflect.EnumType {
	return &file_DanubeApi_proto_enumTypes[2]
}

func (x ConsumerRequest_SubscriptionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsumerRequest_SubscriptionType.Descriptor instead.
func (ConsumerRequest_SubscriptionType) EnumDescriptor() ([]byte, []int) {
	return file_DanubeApi_proto_rawDescGZIP(), []int{4, 0}
}

type TopicLookupResponse_LookupType int32

const (
	TopicLookupResponse_Redirect TopicLookupResponse_LookupType = 0
	TopicLookupResponse_Connect  TopicLookupResponse_LookupType = 1
	TopicLookupResponse_Failed   TopicLookupResponse_LookupType = 2
)

// Enum value maps for TopicLookupResponse_LookupType.
var (
	TopicLookupResponse_LookupType_name = map[int32]string{
		0: "Redirect",
		1: "Connect",
		2: "Failed",
	}
	TopicLookupResponse_LookupType_value = map[string]int32{
		"Redirect": 0,
		"Connect":  1,
		"Failed":   2,
	}
)

func (x TopicLookupResponse_LookupType) Enum() *TopicLookupResponse_LookupType {
	p := new(TopicLookupResponse_LookupType)
	*p = x
	return p
}

func (x TopicLookupResponse_LookupType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TopicLookupResponse_LookupType) Descriptor() protoreflect.EnumDescriptor {
	return file_DanubeApi_proto_enumTypes[3].Descriptor()
}

func (TopicLookupResponse_LookupType) Type() protoreflect.EnumType {
	return &file_DanubeApi_proto_enumTypes[3]
}

func (x TopicLookupResponse_LookupType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TopicLookupResponse_LookupType.Descriptor instead.
func (TopicLookupResponse_LookupType) EnumDescriptor() ([]byte, []int) {
	return file_DanubeApi_proto_rawDescGZIP(), []int{12, 0}
}

type HealthCheckRequest_ClientType int32

const (
	HealthCheckRequest_Producer HealthCheckRequest_ClientType = 0
	HealthCheckRequest_Consumer HealthCheckRequest_ClientType = 1
)

// Enum value maps for HealthCheckRequest_ClientType.
var (
	HealthCheckRequest_ClientType_name = map[int32]string{
		0: "Producer",
		1: "Consumer",
	}
	HealthCheckRequest_ClientType_value = map[string]int32{
		"Producer": 0,
		"Consumer": 1,
	}
)

func (x HealthCheckRequest_ClientType) Enum() *HealthCheckRequest_ClientType {
	p := new(HealthCheckRequest_ClientType)
	*p = x
	return p
}

func (x HealthCheckRequest_ClientType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckRequest_ClientType) Descriptor() protoreflect.EnumDescriptor {
	return file_DanubeApi_proto_enumTypes[4].Descriptor()
}

func (HealthCheckRequest_ClientType) Type() protoreflect.EnumType {
	return &file_DanubeApi_proto_enumTypes[4]
}

func (x HealthCheckRequest_ClientType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckRequest_ClientType.Descriptor instead.
func (HealthCheckRequest_ClientType) EnumDescriptor() ([]byte, []int) {
	return file_DanubeApi_proto_rawDescGZIP(), []int{14, 0}
}

type HealthCheckResponse_ClientStatus int32

const (
	HealthCheckResponse_OK    HealthCheckResponse_ClientStatus = 0
	HealthCheckResponse_CLOSE HealthCheckResponse_ClientStatus = 1
)

// Enum value maps for HealthCheckResponse_ClientStatus.
var (
	HealthCheckResponse_ClientStatus_name = map[int32]string{
		0: "OK",
		1: "CLOSE",
	}
	HealthCheckResponse_ClientStatus_value = map[string]int32{
		"OK":    0,
		"CLOSE": 1,
	}
)

func (x HealthCheckResponse_ClientStatus) Enum() *HealthCheckResponse_ClientStatus {
	p := new(HealthCheckResponse_ClientStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ClientStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ClientStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_DanubeApi_proto_enumTypes[5].Descriptor()
}

func (HealthCheckResponse_ClientStatus) Type() protoreflect.EnumType {
	return &file_DanubeApi_proto_enumTypes[5]
}

func (x HealthCheckResponse_ClientStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ClientStatus.Descriptor instead.
func (HealthCheckResponse_ClientStatus) EnumDescriptor() ([]byte, []int) {
	return file_DanubeApi_proto_rawDescGZIP(), []int{15, 0}
}

// Create Producer request
type ProducerRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RequestId          uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ProducerName       string                 `protobuf:"bytes,2,opt,name=producer_name,json=producerName,proto3" json:"producer_name,omitempty"`
	TopicName          string                 `protobuf:"bytes,3,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	SchemaRef          *SchemaReference       `protobuf:"bytes,4,opt,name=schema_ref,json=schemaRef,proto3" json:"schema_ref,omitempty"`
	ProducerAccessMode ProducerAccessMode     `protobuf:"varint,5,opt,name=producer_access_mode,json=producerAccessMode,proto3,enum=danube.ProducerAccessMode" json:"producer_access_mode,omitempty"`
	DispatchStrategy   DispatchStrategy       `protobuf:"varint,6,opt,name=dispatch_strategy,json=dispatchStrategy,proto3,enum=danube.DispatchStrategy" json:"dispatch_strategy,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProducerRequest) Reset() {
	*x = ProducerRequest{}
	mi := &file_DanubeApi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProducerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProducerRequest) ProtoMessage() {}

func (x *ProducerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_DanubeApi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProducerRequest.ProtoReflect.Descriptor instead.
func (*ProducerRequest) Descriptor() ([]byte, []int) {
	return file_DanubeApi_proto_rawDescGZIP(), []int{0}
}

func (x *ProducerRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ProducerRequest) GetProducerName() string {
	if x != nil {
		return x.ProducerName
	}
	return ""
}

func (x *ProducerRequest) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *ProducerRequest) GetSchemaRef() *SchemaReference {
	if x != nil {
		return x.SchemaRef
	}
	return nil
}

func (x *ProducerRequest) GetProducerAccessMode() ProducerAccessMode {
	if x != nil {
		return x.ProducerAccessMode
	}
	return ProducerAccessMode_Shared
}

func (x *ProducerRequest) GetDispatchStrategy() DispatchStrategy {
	if x != nil {
		return x.DispatchStrategy
	}
	return DispatchStrategy_NonReliable
}

// Reference to a schema in the schema registry
type SchemaReference struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Subject string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"` // Subject name (usually topic name)
	// Types that are valid to be assigned to VersionRef:
	//
	//	*SchemaReference_UseLatest
	//	*SchemaReference_PinnedVersion
	//	*SchemaReference_MinVersion
	VersionRef    isSchemaReference_VersionRef `protobuf_oneof:"version_ref"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaReference) Reset() {
	*x = SchemaReference{}
	mi := &file_DanubeApi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaReference) ProtoMessage() {}

func (x *SchemaReference) ProtoReflect() protoreflect.Message {
	mi := &file_DanubeApi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaReference.ProtoReflect.Descriptor instead.
func (*SchemaReference) Descriptor() ([]byte, []int) {
	return file_DanubeApi_proto_rawDescGZIP(), []int{1}
}

func (x *SchemaReference) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SchemaReference) GetVersionRef() isSchemaReference_VersionRef {
	if x != nil {
		return x.VersionRef
	}
	return nil
}

func (x *SchemaReference) GetUseLatest() bool {
	if x != nil {
		if x, ok := x.VersionRef.(*SchemaReference_UseLatest); ok {
			return x.UseLatest
		}
	}
	return false
}

func (x *SchemaReference) GetPinnedVersion() uint32 {
	if x != nil {
		if x, ok := x.VersionRef.(*SchemaReference_PinnedVersion); ok {
			return x.PinnedVersion
		}
	}
	return 0
}

func (x *SchemaReference) GetMinVersion() uint32 {
	if x != nil {
		if x, ok := x.VersionRef.(*SchemaReference_MinVersion); ok {
			return x.MinVersion
		}
	}
	return 0
}

type isSchemaReference_VersionRef interface {
	isSchemaReference_VersionRef()
}

type SchemaReference_UseLatest struct {
	UseLatest bool `protobuf:"varint,2,opt,name=use_latest,json=useLatest,proto3,oneof"` // Use latest version (true)
}

type SchemaReference_PinnedVersion struct {
	PinnedVersion uint32 `protobuf:"varint,3,opt,name=pinned_version,json=pinnedVersion,proto3,oneof"` // Use specific version number
}

type SchemaReference_MinVersion struct {
	MinVersion uint32 `protobuf:"varint,4,opt,name=min_version,json=minVersion,proto3,oneof"` // Use version >= this number
}

func (*SchemaReference_UseLatest) isSchemaReference_VersionRef() {}

func (*SchemaReference_PinnedVersion) isSchemaReference_VersionRef() {}

func (*SchemaReference_MinVersion) isSchemaReference_VersionRef() {}

// Create Producer response
type ProducerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ProducerId    uint64                 `protobuf:"varint,2,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	ProducerName  string                 `protobuf:"bytes,3,opt,name=producer_name,json=producerName,proto3" json:"producer_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProducerResponse) Reset() {
	*x = ProducerResponse{}
	mi := &file_DanubeApi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProducerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProducerResponse) ProtoMessage() {}

func (x *ProducerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_DanubeApi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProducerResponse.ProtoReflect.Descriptor instead.
func (*ProducerResponse) Descriptor() ([]byte, []int) {
	return file_DanubeApi_proto_rawDescGZIP(), []int{2}
}

func (x *ProducerResponse) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ProducerResponse) GetProducerId() uint64 {
	if x != nil {
		return x.ProducerId
	}
	return 0
}

func (x *ProducerResponse) GetProducerName() string {
	if x != nil {
		return x.ProducerName
	}
	return ""
}

// Producer receive acknowledge for the sent message
type MessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	mi := &file_DanubeApi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_DanubeApi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_DanubeApi_proto_rawDescGZIP(), []int{3}
}

func (x *MessageResponse) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

// Create Consumer request
type ConsumerRequest struct {
	state            protoimpl.MessageState           `protogen:"open.v1"`
	RequestId        uint64                           `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TopicName        string                           `protobuf:"bytes,2,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	ConsumerName     string                           `protobuf:"bytes,3,opt,name=consumer_name,json=consumerName,proto3" json:"consumer_name,omitempty"`
	Subscription     string                           `protobuf:"bytes,4,opt,name=subscription,proto3" json:"subscription,omitempty"`
	SubscriptionType ConsumerRequest_SubscriptionType `protobuf:"varint,5,opt,name=subscription_type,json=subscriptionType,proto3,enum=danube.ConsumerRequest_SubscriptionType" json:"subscription_type,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConsumerRequest) Reset() {
	*x = ConsumerRequest{}
	mi := &file_DanubeApi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerRequest) ProtoMessage() {}

func (x *ConsumerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_DanubeApi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerRequest.ProtoReflect.Descriptor instead.
func (*ConsumerRequest) Descriptor() ([]byte, []int) {
	return file_DanubeApi_proto_rawDescGZIP(), []int{4}
}

func (x *ConsumerRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ConsumerRequest) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *ConsumerRequest) GetConsumerName() string {
	if x != nil {
		return x.ConsumerName
	}
	return ""
}

func (x *ConsumerRequest) GetSubscription() string {
	if x != nil {
		return x.Subscription
	}
	return ""
}

func (x *ConsumerRequest) GetSubscriptionType() ConsumerRequest_SubscriptionType {
	if x != nil {
		return x.SubscriptionType
	}
	return ConsumerRequest_Exclusive
}

// Create Consumer response
type ConsumerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ConsumerId    uint64                 `protobuf:"varint,2,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	ConsumerName  string                 `protobuf:"bytes,3,opt,name=consumer_name,json=consumerName,proto3" json:"consumer_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumerResponse) Reset() {
	*x = ConsumerResponse{}
	mi := &file_DanubeApi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerResponse) ProtoMessage() {}

func (x *ConsumerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_DanubeApi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerResponse.ProtoReflect.Descriptor instead.
func (*ConsumerResponse) Descriptor() ([]byte, []int) {
	return file_DanubeApi_proto_rawDescGZIP(), []int{5}
}

func (x *ConsumerResponse) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ConsumerResponse) GetConsumerId() uint64 {
	if x != nil {
		return x.ConsumerId
	}
	return 0
}

func (x *ConsumerResponse) GetConsumerName() string {
	if x != nil {
		return x.ConsumerName
	}
	return ""
}

type ReceiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ConsumerId    uint64                 `protobuf:"varint,2,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveRequest) Reset() {
	*x = ReceiveRequest{}
	mi := &file_DanubeApi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveRequest) ProtoMessage() {}

func (x *ReceiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_DanubeApi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveRequest.ProtoReflect.Descriptor instead.
func (*ReceiveRequest) Descriptor() ([]byte, []int) {
	return file_DanubeApi_proto_rawDescGZIP(), []int{6}
}

func (x *ReceiveRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ReceiveRequest) GetConsumerId() uint64 {
	if x != nil {
		return x.ConsumerId
	}
	return 0
}

// The message that is sent by producer to topic and then to consumer
type StreamMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique ID for tracking the message request
	RequestId uint64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Identifies the message, associated with a unique topic, subscription and the broker
	MsgId *MsgID `protobuf:"bytes,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	// The actual payload of the message
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// Timestamp for when the message was published
	PublishTime uint64 `protobuf:"varint,4,opt,name=publish_time,json=publishTime,proto3" json:"publish_time,omitempty"`
	// Identifies the producer’s name
	ProducerName string `protobuf:"bytes,5,opt,name=producer_name,json=producerName,proto3" json:"producer_name,omitempty"`
	// Subscription name the consumer is subscribed to
	SubscriptionName string `protobuf:"bytes,6,opt,name=subscription_name,json=subscriptionName,proto3" json:"subscription_name,omitempty"`
	// User-defined properties/attributes
	Attributes map[string]string `protobuf:"bytes,7,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// NEW: Schema identification for registry-based schemas
	SchemaId      *uint64 `protobuf:"varint,8,opt,name=schema_id,json=schemaId,proto3,oneof" json:"schema_id,omitempty"`                // Global schema ID from registry
	SchemaVersion *uint32 `protobuf:"varint,9,opt,name=schema_version,json=schemaVersion,proto3,oneof" json:"schema_version,omitempty"` // Schema version number
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessage) Reset() {
	*x = StreamMessage{}
	mi := &file_DanubeApi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessage) ProtoMessage() {}

func (x *StreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_DanubeApi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessage.ProtoReflect.Descriptor instead.
func (*StreamMessage) Descriptor() ([]byte, []int) {
	return file_DanubeApi_proto_rawDescGZIP(), []int{7}
}

func (x *StreamMessage) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *StreamMessage) GetMsgId() *MsgID {
	if x != nil {
		return x.MsgId
	}
	return nil
}

func (x *StreamMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamMessage) GetPublishTime() uint64 {
	if x != nil {
		return x.PublishTime
	}
	return 0
}

func (x *StreamMessage) GetProducerName() string {
	if x != nil {
		return x.ProducerName
	}
	return ""
}

func (x *StreamMessage) GetSubscriptionName() string {
	if x != nil {
		return x.SubscriptionName
	}
	return ""
}

func (x *StreamMessage) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *StreamMessage) GetSchemaId() uint64 {
	if x != nil && x.SchemaId != nil {
		return *x.SchemaId
	}
	return 0
}

func (x *StreamMessage) GetSchemaVersion() uint32 {
	if x != nil && x.SchemaVersion != nil {
		return *x.SchemaVersion
	}
	return 0
}

// Unique ID of the message
type MsgID struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifies the producer, associated with a unique topic
	ProducerId uint64 `protobuf:"varint,1,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	// Topic name the message is published to
	TopicName string `protobuf:"bytes,2,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	// Broker address
	BrokerAddr string `protobuf:"bytes,3,opt,name=broker_addr,json=brokerAddr,proto3" json:"broker_addr,omitempty"`
	// Offset within the topic
	TopicOffset   uint64 `protobuf:"varint,5,opt,name=topic_offset,json=topicOffset,proto3" json:"topic_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgID) Reset() {
	*x = MsgID{}
	mi := &file_DanubeApi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgID) ProtoMessage() {}

func (x *MsgID) ProtoReflect() protoreflect.Message {
	mi := &file_DanubeApi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgID.ProtoReflect.Descriptor instead.
func (*MsgID) Descriptor() ([]byte, []int) {
	return file_DanubeApi_proto_rawDescGZIP(), []int{8}
}

func (x *MsgID) GetProducerId() uint64 {
	if x != nil {
		return x.ProducerId
	}
	return 0
}

func (x *MsgID) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *MsgID) GetBrokerAddr() string {
	if x != nil {
		return x.BrokerAddr
	}
	return ""
}

func (x *MsgID) GetTopicOffset() uint64 {
	if x != nil {
		return x.TopicOffset
	}
	return 0
}

type AckRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Identifies the message, associated with a unique topic, subscription and the broker
	MsgId *MsgID `protobuf:"bytes,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	// Subscription name the consumer is subscribed to
	SubscriptionName string `protobuf:"bytes,3,opt,name=subscription_name,json=subscriptionName,proto3" json:"subscription_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_DanubeApi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_DanubeApi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_DanubeApi_proto_rawDescGZIP(), []int{9}
}

func (x *AckRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *AckRequest) GetMsgId() *MsgID {
	if x != nil {
		return x.MsgId
	}
	return nil
}

func (x *AckRequest) GetSubscriptionName() string {
	if x != nil {
		return x.SubscriptionName
	}
	return ""
}

type AckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	mi := &file_DanubeApi_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_DanubeApi_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_DanubeApi_proto_rawDescGZIP(), []int{10}
}

func (x *AckResponse) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type TopicLookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicLookupRequest) Reset() {
	*x = TopicLookupRequest{}
	mi := &file_DanubeApi_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicLookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicLookupRequest) ProtoMessage() {}

func (x *TopicLookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_DanubeApi_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicLookupRequest.ProtoReflect.Descriptor instead.
func (*TopicLookupRequest) Descriptor() ([]byte, []int) {
	return file_DanubeApi_proto_rawDescGZIP(), []int{11}
}

func (x *TopicLookupRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *TopicLookupRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type TopicLookupResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	RequestId     uint64                         `protobuf:"varint,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ResponseType  TopicLookupResponse_LookupType `protobuf:"varint,4,opt,name=response_type,json=responseType,proto3,enum=danube.TopicLookupResponse_LookupType" json:"response_type,omitempty"`
	ConnectUrl    string                         `protobuf:"bytes,5,opt,name=connect_url,json=connectUrl,proto3" json:"connect_url,omitempty"`
	BrokerUrl     string                         `protobuf:"bytes,6,opt,name=broker_url,json=brokerUrl,proto3" json:"broker_url,omitempty"`
	Proxy         bool                           `protobuf:"varint,7,opt,name=proxy,proto3" json:"proxy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicLookupResponse) Reset() {
	*x = TopicLookupResponse{}
	mi := &file_DanubeApi_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicLookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicLookupResponse) ProtoMessage() {}

func (x *TopicLookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_DanubeApi_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicLookupResponse.ProtoReflect.Descriptor instead.
func (*TopicLookupResponse) Descriptor() ([]byte, []int) {
	return file_DanubeApi_proto_rawDescGZIP(), []int{12}
}

func (x *TopicLookupResponse) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *TopicLookupResponse) GetResponseType() TopicLookupResponse_LookupType {
	if x != nil {
		return x.ResponseType
	}
	return TopicLookupResponse_Redirect
}

func (x *TopicLookupResponse) GetConnectUrl() string {
	if x != nil {
		return x.ConnectUrl
	}
	return ""
}

func (x *TopicLookupResponse) GetBrokerUrl() string {
	if x != nil {
		return x.BrokerUrl
	}
	return ""
}

func (x *TopicLookupResponse) GetProxy() bool {
	if x != nil {
		return x.Proxy
	}
	return false
}

type TopicPartitionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Partitions    []string               `protobuf:"bytes,2,rep,name=partitions,proto3" json:"partitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicPartitionsResponse) Reset() {
	*x = TopicPartitionsResponse{}
	mi := &file_DanubeApi_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicPartitionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicPartitionsResponse) ProtoMessage() {}

func (x *TopicPartitionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_DanubeApi_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicPartitionsResponse.ProtoReflect.Descriptor instead.
func (*TopicPartitionsResponse) Descriptor() ([]byte, []int) {
	return file_DanubeApi_proto_rawDescGZIP(), []int{13}
}

func (x *TopicPartitionsResponse) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *TopicPartitionsResponse) GetPartitions() []string {
	if x != nil {
		return x.Partitions
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	RequestId     uint64                        `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Client        HealthCheckRequest_ClientType `protobuf:"varint,2,opt,name=client,proto3,enum=danube.HealthCheckRequest_ClientType" json:"client,omitempty"`
	Id            uint64                        `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_DanubeApi_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_DanubeApi_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_DanubeApi_proto_rawDescGZIP(), []int{14}
}

func (x *HealthCheckRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *HealthCheckRequest) GetClient() HealthCheckRequest_ClientType {
	if x != nil {
		return x.Client
	}
	return HealthCheckRequest_Producer
}

func (x *HealthCheckRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Status        HealthCheckResponse_ClientStatus `protobuf:"varint,1,opt,name=status,proto3,enum=danube.HealthCheckResponse_ClientStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_DanubeApi_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_DanubeApi_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_DanubeApi_proto_rawDescGZIP(), []int{15}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ClientStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_OK
}

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_DanubeApi_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_DanubeApi_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_DanubeApi_proto_rawDescGZIP(), []int{16}
}

func (x *AuthRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_DanubeApi_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_DanubeApi_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_DanubeApi_proto_rawDescGZIP(), []int{17}
}

func (x *AuthResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_DanubeApi_proto protoreflect.FileDescriptor

const file_DanubeApi_proto_rawDesc = "" +
	"\n" +
	"\x0fDanubeApi.proto\x12\x06danube\"\xc1\x02\n" +
	"\x0fProducerRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12#\n" +
	"\rproducer_name\x18\x02 \x01(\tR\fproducerName\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x03 \x01(\tR\ttopicName\x126\n" +
	"\n" +
	"schema_ref\x18\x04 \x01(\v2\x17.danube.SchemaReferenceR\tschemaRef\x12L\n" +
	"\x14producer_access_mode\x18\x05 \x01(\x0e2\x1a.danube.ProducerAccessModeR\x12producerAccessMode\x12E\n" +
	"\x11dispatch_strategy\x18\x06 \x01(\x0e2\x18.danube.DispatchStrategyR\x10dispatchStrategy\"\xa7\x01\n" +
	"\x0fSchemaReference\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1f\n" +
	"\n" +
	"use_latest\x18\x02 \x01(\bH\x00R\tuseLatest\x12'\n" +
	"\x0epinned_version\x18\x03 \x01(\rH\x00R\rpinnedVersion\x12!\n" +
	"\vmin_version\x18\x04 \x01(\rH\x00R\n" +
	"minVersionB\r\n" +
	"\vversion_ref\"w\n" +
	"\x10ProducerResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x1f\n" +
	"\vproducer_id\x18\x02 \x01(\x04R\n" +
	"producerId\x12#\n" +
	"\rproducer_name\x18\x03 \x01(\tR\fproducerName\"0\n" +
	"\x0fMessageResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\"\xac\x02\n" +
	"\x0fConsumerRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x02 \x01(\tR\ttopicName\x12#\n" +
	"\rconsumer_name\x18\x03 \x01(\tR\fconsumerName\x12\"\n" +
	"\fsubscription\x18\x04 \x01(\tR\fsubscription\x12U\n" +
	"\x11subscription_type\x18\x05 \x01(\x0e2(.danube.ConsumerRequest.SubscriptionTypeR\x10subscriptionType\";\n" +
	"\x10SubscriptionType\x12\r\n" +
	"\tExclusive\x10\x00\x12\n" +
	"\n" +
	"\x06Shared\x10\x01\x12\f\n" +
	"\bFailover\x10\x02\"w\n" +
	"\x10ConsumerResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x1f\n" +
	"\vconsumer_id\x18\x02 \x01(\x04R\n" +
	"consumerId\x12#\n" +
	"\rconsumer_name\x18\x03 \x01(\tR\fconsumerName\"P\n" +
	"\x0eReceiveRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x1f\n" +
	"\vconsumer_id\x18\x02 \x01(\x04R\n" +
	"consumerId\"\xd8\x03\n" +
	"\rStreamMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12$\n" +
	"\x06msg_id\x18\x02 \x01(\v2\r.danube.MsgIDR\x05msgId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12!\n" +
	"\fpublish_time\x18\x04 \x01(\x04R\vpublishTime\x12#\n" +
	"\rproducer_name\x18\x05 \x01(\tR\fproducerName\x12+\n" +
	"\x11subscription_name\x18\x06 \x01(\tR\x10subscriptionName\x12E\n" +
	"\n" +
	"attributes\x18\a \x03(\v2%.danube.StreamMessage.AttributesEntryR\n" +
	"attributes\x12 \n" +
	"\tschema_id\x18\b \x01(\x04H\x00R\bschemaId\x88\x01\x01\x12*\n" +
	"\x0eschema_version\x18\t \x01(\rH\x01R\rschemaVersion\x88\x01\x01\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_schema_idB\x11\n" +
	"\x0f_schema_version\"\x8b\x01\n" +
	"\x05MsgID\x12\x1f\n" +
	"\vproducer_id\x18\x01 \x01(\x04R\n" +
	"producerId\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x02 \x01(\tR\ttopicName\x12\x1f\n" +
	"\vbroker_addr\x18\x03 \x01(\tR\n" +
	"brokerAddr\x12!\n" +
	"\ftopic_offset\x18\x05 \x01(\x04R\vtopicOffset\"~\n" +
	"\n" +
	"AckRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12$\n" +
	"\x06msg_id\x18\x02 \x01(\v2\r.danube.MsgIDR\x05msgId\x12+\n" +
	"\x11subscription_name\x18\x03 \x01(\tR\x10subscriptionName\",\n" +
	"\vAckResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\"I\n" +
	"\x12TopicLookupRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\"\x8c\x02\n" +
	"\x13TopicLookupResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\x04R\trequestId\x12K\n" +
	"\rresponse_type\x18\x04 \x01(\x0e2&.danube.TopicLookupResponse.LookupTypeR\fresponseType\x12\x1f\n" +
	"\vconnect_url\x18\x05 \x01(\tR\n" +
	"connectUrl\x12\x1d\n" +
	"\n" +
	"broker_url\x18\x06 \x01(\tR\tbrokerUrl\x12\x14\n" +
	"\x05proxy\x18\a \x01(\bR\x05proxy\"3\n" +
	"\n" +
	"LookupType\x12\f\n" +
	"\bRedirect\x10\x00\x12\v\n" +
	"\aConnect\x10\x01\x12\n" +
	"\n" +
	"\x06Failed\x10\x02\"X\n" +
	"\x17TopicPartitionsResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x1e\n" +
	"\n" +
	"partitions\x18\x02 \x03(\tR\n" +
	"partitions\"\xac\x01\n" +
	"\x12HealthCheckRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12=\n" +
	"\x06client\x18\x02 \x01(\x0e2%.danube.HealthCheckRequest.ClientTypeR\x06client\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x04R\x02id\"(\n" +
	"\n" +
	"ClientType\x12\f\n" +
	"\bProducer\x10\x00\x12\f\n" +
	"\bConsumer\x10\x01\"z\n" +
	"\x13HealthCheckResponse\x12@\n" +
	"\x06status\x18\x01 \x01(\x0e2(.danube.HealthCheckResponse.ClientStatusR\x06status\"!\n" +
	"\fClientStatus\x12\x06\n" +
	"\x02OK\x10\x00\x12\t\n" +
	"\x05CLOSE\x10\x01\"&\n" +
	"\vAuthRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\"$\n" +
	"\fAuthResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token*/\n" +
	"\x12ProducerAccessMode\x12\n" +
	"\n" +
	"\x06Shared\x10\x00\x12\r\n" +
	"\tExclusive\x10\x01*1\n" +
	"\x10DispatchStrategy\x12\x0f\n" +
	"\vNonReliable\x10\x00\x12\f\n" +
	"\bReliable\x10\x012\x95\x01\n" +
	"\x0fProducerService\x12C\n" +
	"\x0eCreateProducer\x12\x17.danube.ProducerRequest\x1a\x18.danube.ProducerResponse\x12=\n" +
	"\vSendMessage\x12\x15.danube.StreamMessage\x1a\x17.danube.MessageResponse2\xc5\x01\n" +
	"\x0fConsumerService\x12>\n" +
	"\tSubscribe\x12\x17.danube.ConsumerRequest\x1a\x18.danube.ConsumerResponse\x12B\n" +
	"\x0fReceiveMessages\x12\x16.danube.ReceiveRequest\x1a\x15.danube.StreamMessage0\x01\x12.\n" +
	"\x03Ack\x12\x12.danube.AckRequest\x1a\x13.danube.AckResponse2\xa3\x01\n" +
	"\tDiscovery\x12F\n" +
	"\vTopicLookup\x12\x1a.danube.TopicLookupRequest\x1a\x1b.danube.TopicLookupResponse\x12N\n" +
	"\x0fTopicPartitions\x12\x1a.danube.TopicLookupRequest\x1a\x1f.danube.TopicPartitionsResponse2U\n" +
	"\vHealthCheck\x12F\n" +
	"\vHealthCheck\x12\x1a.danube.HealthCheckRequest\x1a\x1b.danube.HealthCheckResponse2H\n" +
	"\vAuthService\x129\n" +
	"\fAuthenticate\x12\x13.danube.AuthRequest\x1a\x14.danube.AuthResponseB-Z+github.com/danube-messaging/danube-go/protob\x06proto3"

var (
	file_DanubeApi_proto_rawDescOnce sync.Once
	file_DanubeApi_proto_rawDescData []byte
)

func file_DanubeApi_proto_rawDescGZIP() []byte {
	file_DanubeApi_proto_rawDescOnce.Do(func() {
		file_DanubeApi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_DanubeApi_proto_rawDesc), len(file_DanubeApi_proto_rawDesc)))
	})
	return file_DanubeApi_proto_rawDescData
}

var file_DanubeApi_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_DanubeApi_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_DanubeApi_proto_goTypes = []any{
	(ProducerAccessMode)(0),               // 0: danube.ProducerAccessMode
	(DispatchStrategy)(0),                 // 1: danube.DispatchStrategy
	(ConsumerRequest_SubscriptionType)(0), // 2: danube.ConsumerRequest.SubscriptionType
	(TopicLookupResponse_LookupType)(0),   // 3: danube.TopicLookupResponse.LookupType
	(HealthCheckRequest_ClientType)(0),    // 4: danube.HealthCheckRequest.ClientType
	(HealthCheckResponse_ClientStatus)(0), // 5: danube.HealthCheckResponse.ClientStatus
	(*ProducerRequest)(nil),               // 6: danube.ProducerRequest
	(*SchemaReference)(nil),               // 7: danube.SchemaReference
	(*ProducerResponse)(nil),              // 8: danube.ProducerResponse
	(*MessageResponse)(nil),               // 9: danube.MessageResponse
	(*ConsumerRequest)(nil),               // 10: danube.ConsumerRequest
	(*ConsumerResponse)(nil),              // 11: danube.ConsumerResponse
	(*ReceiveRequest)(nil),                // 12: danube.ReceiveRequest
	(*StreamMessage)(nil),                 // 13: danube.StreamMessage
	(*MsgID)(nil),                         // 14: danube.MsgID
	(*AckRequest)(nil),                    // 15: danube.AckRequest
	(*AckResponse)(nil),                   // 16: danube.AckResponse
	(*TopicLookupRequest)(nil),            // 17: danube.TopicLookupRequest
	(*TopicLookupResponse)(nil),           // 18: danube.TopicLookupResponse
	(*TopicPartitionsResponse)(nil),       // 19: danube.TopicPartitionsResponse
	(*HealthCheckRequest)(nil),            // 20: danube.HealthCheckRequest
	(*HealthCheckResponse)(nil),           // 21: danube.HealthCheckResponse
	(*AuthRequest)(nil),                   // 22: danube.AuthRequest
	(*AuthResponse)(nil),                  // 23: danube.AuthResponse
	nil,                                   // 24: danube.StreamMessage.AttributesEntry
}
var file_DanubeApi_proto_depIdxs = []int32{
	7,  // 0: danube.ProducerRequest.schema_ref:type_name -> danube.SchemaReference
	0,  // 1: danube.ProducerRequest.producer_access_mode:type_name -> danube.ProducerAccessMode
	1,  // 2: danube.ProducerRequest.dispatch_strategy:type_name -> danube.DispatchStrategy
	2,  // 3: danube.ConsumerRequest.subscription_type:type_name -> danube.ConsumerRequest.SubscriptionType
	14, // 4: danube.StreamMessage.msg_id:type_name -> danube.MsgID
	24, // 5: danube.StreamMessage.attributes:type_name -> danube.StreamMessage.AttributesEntry
	14, // 6: danube.AckRequest.msg_id:type_name -> danube.MsgID
	3,  // 7: danube.TopicLookupResponse.response_type:type_name -> danube.TopicLookupResponse.LookupType
	4,  // 8: danube.HealthCheckRequest.client:type_name -> danube.HealthCheckRequest.ClientType
	5,  // 9: danube.HealthCheckResponse.status:type_name -> danube.HealthCheckResponse.ClientStatus
	6,  // 10: danube.ProducerService.CreateProducer:input_type -> danube.ProducerRequest
	13, // 11: danube.ProducerService.SendMessage:input_type -> danube.StreamMessage
	10, // 12: danube.ConsumerService.Subscribe:input_type -> danube.ConsumerRequest
	12, // 13: danube.ConsumerService.ReceiveMessages:input_type -> danube.ReceiveRequest
	15, // 14: danube.ConsumerService.Ack:input_type -> danube.AckRequest
	17, // 15: danube.Discovery.TopicLookup:input_type -> danube.TopicLookupRequest
	17, // 16: danube.Discovery.TopicPartitions:input_type -> danube.TopicLookupRequest
	20, // 17: danube.HealthCheck.HealthCheck:input_type -> danube.HealthCheckRequest
	22, // 18: danube.AuthService.Authenticate:input_type -> danube.AuthRequest
	8,  // 19: danube.ProducerService.CreateProducer:output_type -> danube.ProducerResponse
	9,  // 20: danube.ProducerService.SendMessage:output_type -> danube.MessageResponse
	11, // 21: danube.ConsumerService.Subscribe:output_type -> danube.ConsumerResponse
	13, // 22: danube.ConsumerService.ReceiveMessages:output_type -> danube.StreamMessage
	16, // 23: danube.ConsumerService.Ack:output_type -> danube.AckResponse
	18, // 24: danube.Discovery.TopicLookup:output_type -> danube.TopicLookupResponse
	19, // 25: danube.Discovery.TopicPartitions:output_type -> danube.TopicPartitionsResponse
	21, // 26: danube.HealthCheck.HealthCheck:output_type -> danube.HealthCheckResponse
	23, // 27: danube.AuthService.Authenticate:output_type -> danube.AuthResponse
	19, // [19:28] is the sub-list for method output_type
	10, // [10:19] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_DanubeApi_proto_init() }
func file_DanubeApi_proto_init() {
	if File_DanubeApi_proto != nil {
		return
	}
	file_DanubeApi_proto_msgTypes[1].OneofWrappers = []any{
		(*SchemaReference_UseLatest)(nil),
		(*SchemaReference_PinnedVersion)(nil),
		(*SchemaReference_MinVersion)(nil),
	}
	file_DanubeApi_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_DanubeApi_proto_rawDesc), len(file_DanubeApi_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_DanubeApi_proto_goTypes,
		DependencyIndexes: file_DanubeApi_proto_depIdxs,
		EnumInfos:         file_DanubeApi_proto_enumTypes,
		MessageInfos:      file_DanubeApi_proto_msgTypes,
	}.Build()
	File_DanubeApi_proto = out.File
	file_DanubeApi_proto_goTypes = nil
	file_DanubeApi_proto_depIdxs = nil
}
