// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: SchemaRegistry.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to register a new schema
type RegisterSchemaRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Subject          string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`                                           // Subject name (defaults to topic name)
	SchemaType       string                 `protobuf:"bytes,2,opt,name=schema_type,json=schemaType,proto3" json:"schema_type,omitempty"`                   // "avro", "json_schema", "protobuf", "bytes", "string", "number"
	SchemaDefinition []byte                 `protobuf:"bytes,3,opt,name=schema_definition,json=schemaDefinition,proto3" json:"schema_definition,omitempty"` // Schema content (JSON for Avro/JSON Schema, proto for Protobuf)
	Description      string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                                   // Human-readable description
	CreatedBy        string                 `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`                      // Creator identifier
	Tags             []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`                                                 // Tags for categorization
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterSchemaRequest) Reset() {
	*x = RegisterSchemaRequest{}
	mi := &file_SchemaRegistry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSchemaRequest) ProtoMessage() {}

func (x *RegisterSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_SchemaRegistry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSchemaRequest.ProtoReflect.Descriptor instead.
func (*RegisterSchemaRequest) Descriptor() ([]byte, []int) {
	return file_SchemaRegistry_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterSchemaRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *RegisterSchemaRequest) GetSchemaType() string {
	if x != nil {
		return x.SchemaType
	}
	return ""
}

func (x *RegisterSchemaRequest) GetSchemaDefinition() []byte {
	if x != nil {
		return x.SchemaDefinition
	}
	return nil
}

func (x *RegisterSchemaRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RegisterSchemaRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *RegisterSchemaRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// Response after registering a schema
type RegisterSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaId      uint64                 `protobuf:"varint,1,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`               // Globally unique schema ID
	Version       uint32                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`                                 // Version number for this subject
	IsNewVersion  bool                   `protobuf:"varint,3,opt,name=is_new_version,json=isNewVersion,proto3" json:"is_new_version,omitempty"` // false if exact schema already exists
	Fingerprint   string                 `protobuf:"bytes,4,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`                          // SHA-256 hash of schema for client caching
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterSchemaResponse) Reset() {
	*x = RegisterSchemaResponse{}
	mi := &file_SchemaRegistry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSchemaResponse) ProtoMessage() {}

func (x *RegisterSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_SchemaRegistry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSchemaResponse.ProtoReflect.Descriptor instead.
func (*RegisterSchemaResponse) Descriptor() ([]byte, []int) {
	return file_SchemaRegistry_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterSchemaResponse) GetSchemaId() uint64 {
	if x != nil {
		return x.SchemaId
	}
	return 0
}

func (x *RegisterSchemaResponse) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RegisterSchemaResponse) GetIsNewVersion() bool {
	if x != nil {
		return x.IsNewVersion
	}
	return false
}

func (x *RegisterSchemaResponse) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

// Request to get a schema by ID
type GetSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaId      uint64                 `protobuf:"varint,1,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"` // Global schema ID
	Version       *uint32                `protobuf:"varint,2,opt,name=version,proto3,oneof" json:"version,omitempty"`             // Optional version, if omitted returns latest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaRequest) Reset() {
	*x = GetSchemaRequest{}
	mi := &file_SchemaRegistry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaRequest) ProtoMessage() {}

func (x *GetSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_SchemaRegistry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaRequest.ProtoReflect.Descriptor instead.
func (*GetSchemaRequest) Descriptor() ([]byte, []int) {
	return file_SchemaRegistry_proto_rawDescGZIP(), []int{2}
}

func (x *GetSchemaRequest) GetSchemaId() uint64 {
	if x != nil {
		return x.SchemaId
	}
	return 0
}

func (x *GetSchemaRequest) GetVersion() uint32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

// Response containing schema details
type GetSchemaResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SchemaId          uint64                 `protobuf:"varint,1,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	Version           uint32                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Subject           string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	SchemaType        string                 `protobuf:"bytes,4,opt,name=schema_type,json=schemaType,proto3" json:"schema_type,omitempty"`
	SchemaDefinition  []byte                 `protobuf:"bytes,5,opt,name=schema_definition,json=schemaDefinition,proto3" json:"schema_definition,omitempty"`
	Description       string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt         uint64                 `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy         string                 `protobuf:"bytes,8,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Tags              []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	Fingerprint       string                 `protobuf:"bytes,10,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	CompatibilityMode string                 `protobuf:"bytes,11,opt,name=compatibility_mode,json=compatibilityMode,proto3" json:"compatibility_mode,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetSchemaResponse) Reset() {
	*x = GetSchemaResponse{}
	mi := &file_SchemaRegistry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaResponse) ProtoMessage() {}

func (x *GetSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_SchemaRegistry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaResponse.ProtoReflect.Descriptor instead.
func (*GetSchemaResponse) Descriptor() ([]byte, []int) {
	return file_SchemaRegistry_proto_rawDescGZIP(), []int{3}
}

func (x *GetSchemaResponse) GetSchemaId() uint64 {
	if x != nil {
		return x.SchemaId
	}
	return 0
}

func (x *GetSchemaResponse) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetSchemaResponse) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *GetSchemaResponse) GetSchemaType() string {
	if x != nil {
		return x.SchemaType
	}
	return ""
}

func (x *GetSchemaResponse) GetSchemaDefinition() []byte {
	if x != nil {
		return x.SchemaDefinition
	}
	return nil
}

func (x *GetSchemaResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetSchemaResponse) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GetSchemaResponse) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *GetSchemaResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *GetSchemaResponse) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *GetSchemaResponse) GetCompatibilityMode() string {
	if x != nil {
		return x.CompatibilityMode
	}
	return ""
}

// Request to get latest schema for a subject
type GetLatestSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"` // Subject name (usually topic name)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestSchemaRequest) Reset() {
	*x = GetLatestSchemaRequest{}
	mi := &file_SchemaRegistry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestSchemaRequest) ProtoMessage() {}

func (x *GetLatestSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_SchemaRegistry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestSchemaRequest.ProtoReflect.Descriptor instead.
func (*GetLatestSchemaRequest) Descriptor() ([]byte, []int) {
	return file_SchemaRegistry_proto_rawDescGZIP(), []int{4}
}

func (x *GetLatestSchemaRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

// Request to list all versions of a subject
type ListVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionsRequest) Reset() {
	*x = ListVersionsRequest{}
	mi := &file_SchemaRegistry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsRequest) ProtoMessage() {}

func (x *ListVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_SchemaRegistry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListVersionsRequest) Descriptor() ([]byte, []int) {
	return file_SchemaRegistry_proto_rawDescGZIP(), []int{5}
}

func (x *ListVersionsRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

// Response with list of versions
type ListVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*SchemaVersionInfo   `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionsResponse) Reset() {
	*x = ListVersionsResponse{}
	mi := &file_SchemaRegistry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsResponse) ProtoMessage() {}

func (x *ListVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_SchemaRegistry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListVersionsResponse) Descriptor() ([]byte, []int) {
	return file_SchemaRegistry_proto_rawDescGZIP(), []int{6}
}

func (x *ListVersionsResponse) GetVersions() []*SchemaVersionInfo {
	if x != nil {
		return x.Versions
	}
	return nil
}

// Information about a schema version
type SchemaVersionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     uint64                 `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,3,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Fingerprint   string                 `protobuf:"bytes,5,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	SchemaId      uint64                 `protobuf:"varint,6,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaVersionInfo) Reset() {
	*x = SchemaVersionInfo{}
	mi := &file_SchemaRegistry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaVersionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaVersionInfo) ProtoMessage() {}

func (x *SchemaVersionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_SchemaRegistry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaVersionInfo.ProtoReflect.Descriptor instead.
func (*SchemaVersionInfo) Descriptor() ([]byte, []int) {
	return file_SchemaRegistry_proto_rawDescGZIP(), []int{7}
}

func (x *SchemaVersionInfo) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SchemaVersionInfo) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SchemaVersionInfo) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *SchemaVersionInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SchemaVersionInfo) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *SchemaVersionInfo) GetSchemaId() uint64 {
	if x != nil {
		return x.SchemaId
	}
	return 0
}

// Request to check compatibility
type CheckCompatibilityRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Subject             string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	NewSchemaDefinition []byte                 `protobuf:"bytes,2,opt,name=new_schema_definition,json=newSchemaDefinition,proto3" json:"new_schema_definition,omitempty"`
	SchemaType          string                 `protobuf:"bytes,3,opt,name=schema_type,json=schemaType,proto3" json:"schema_type,omitempty"`
	CompatibilityMode   *string                `protobuf:"bytes,4,opt,name=compatibility_mode,json=compatibilityMode,proto3,oneof" json:"compatibility_mode,omitempty"` // Override subject's compatibility mode
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CheckCompatibilityRequest) Reset() {
	*x = CheckCompatibilityRequest{}
	mi := &file_SchemaRegistry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCompatibilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCompatibilityRequest) ProtoMessage() {}

func (x *CheckCompatibilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_SchemaRegistry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCompatibilityRequest.ProtoReflect.Descriptor instead.
func (*CheckCompatibilityRequest) Descriptor() ([]byte, []int) {
	return file_SchemaRegistry_proto_rawDescGZIP(), []int{8}
}

func (x *CheckCompatibilityRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CheckCompatibilityRequest) GetNewSchemaDefinition() []byte {
	if x != nil {
		return x.NewSchemaDefinition
	}
	return nil
}

func (x *CheckCompatibilityRequest) GetSchemaType() string {
	if x != nil {
		return x.SchemaType
	}
	return ""
}

func (x *CheckCompatibilityRequest) GetCompatibilityMode() string {
	if x != nil && x.CompatibilityMode != nil {
		return *x.CompatibilityMode
	}
	return ""
}

// Response with compatibility result
type CheckCompatibilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsCompatible  bool                   `protobuf:"varint,1,opt,name=is_compatible,json=isCompatible,proto3" json:"is_compatible,omitempty"`
	Errors        []string               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"` // Incompatibility reasons if not compatible
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckCompatibilityResponse) Reset() {
	*x = CheckCompatibilityResponse{}
	mi := &file_SchemaRegistry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCompatibilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCompatibilityResponse) ProtoMessage() {}

func (x *CheckCompatibilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_SchemaRegistry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCompatibilityResponse.ProtoReflect.Descriptor instead.
func (*CheckCompatibilityResponse) Descriptor() ([]byte, []int) {
	return file_SchemaRegistry_proto_rawDescGZIP(), []int{9}
}

func (x *CheckCompatibilityResponse) GetIsCompatible() bool {
	if x != nil {
		return x.IsCompatible
	}
	return false
}

func (x *CheckCompatibilityResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

// Request to delete a schema version
type DeleteSchemaVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Version       uint32                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSchemaVersionRequest) Reset() {
	*x = DeleteSchemaVersionRequest{}
	mi := &file_SchemaRegistry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSchemaVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSchemaVersionRequest) ProtoMessage() {}

func (x *DeleteSchemaVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_SchemaRegistry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSchemaVersionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSchemaVersionRequest) Descriptor() ([]byte, []int) {
	return file_SchemaRegistry_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteSchemaVersionRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *DeleteSchemaVersionRequest) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// Response for delete operation
type DeleteSchemaVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSchemaVersionResponse) Reset() {
	*x = DeleteSchemaVersionResponse{}
	mi := &file_SchemaRegistry_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSchemaVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSchemaVersionResponse) ProtoMessage() {}

func (x *DeleteSchemaVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_SchemaRegistry_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSchemaVersionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSchemaVersionResponse) Descriptor() ([]byte, []int) {
	return file_SchemaRegistry_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteSchemaVersionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteSchemaVersionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request to set compatibility mode
type SetCompatibilityModeRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Subject           string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	CompatibilityMode string                 `protobuf:"bytes,2,opt,name=compatibility_mode,json=compatibilityMode,proto3" json:"compatibility_mode,omitempty"` // "none", "backward", "forward", "full"
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SetCompatibilityModeRequest) Reset() {
	*x = SetCompatibilityModeRequest{}
	mi := &file_SchemaRegistry_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCompatibilityModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCompatibilityModeRequest) ProtoMessage() {}

func (x *SetCompatibilityModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_SchemaRegistry_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCompatibilityModeRequest.ProtoReflect.Descriptor instead.
func (*SetCompatibilityModeRequest) Descriptor() ([]byte, []int) {
	return file_SchemaRegistry_proto_rawDescGZIP(), []int{12}
}

func (x *SetCompatibilityModeRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SetCompatibilityModeRequest) GetCompatibilityMode() string {
	if x != nil {
		return x.CompatibilityMode
	}
	return ""
}

// Response for compatibility mode update
type SetCompatibilityModeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCompatibilityModeResponse) Reset() {
	*x = SetCompatibilityModeResponse{}
	mi := &file_SchemaRegistry_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCompatibilityModeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCompatibilityModeResponse) ProtoMessage() {}

func (x *SetCompatibilityModeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_SchemaRegistry_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCompatibilityModeResponse.ProtoReflect.Descriptor instead.
func (*SetCompatibilityModeResponse) Descriptor() ([]byte, []int) {
	return file_SchemaRegistry_proto_rawDescGZIP(), []int{13}
}

func (x *SetCompatibilityModeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetCompatibilityModeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request to configure schema for a topic (admin-only)
type ConfigureTopicSchemaRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	TopicName               string                 `protobuf:"bytes,1,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`                                              // Topic to configure (e.g., "/default/user-events")
	SchemaSubject           string                 `protobuf:"bytes,2,opt,name=schema_subject,json=schemaSubject,proto3" json:"schema_subject,omitempty"`                                  // Schema subject to assign
	ValidationPolicy        string                 `protobuf:"bytes,3,opt,name=validation_policy,json=validationPolicy,proto3" json:"validation_policy,omitempty"`                         // "none", "warn", or "enforce"
	EnablePayloadValidation bool                   `protobuf:"varint,4,opt,name=enable_payload_validation,json=enablePayloadValidation,proto3" json:"enable_payload_validation,omitempty"` // Enable deep payload validation
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ConfigureTopicSchemaRequest) Reset() {
	*x = ConfigureTopicSchemaRequest{}
	mi := &file_SchemaRegistry_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureTopicSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureTopicSchemaRequest) ProtoMessage() {}

func (x *ConfigureTopicSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_SchemaRegistry_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureTopicSchemaRequest.ProtoReflect.Descriptor instead.
func (*ConfigureTopicSchemaRequest) Descriptor() ([]byte, []int) {
	return file_SchemaRegistry_proto_rawDescGZIP(), []int{14}
}

func (x *ConfigureTopicSchemaRequest) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *ConfigureTopicSchemaRequest) GetSchemaSubject() string {
	if x != nil {
		return x.SchemaSubject
	}
	return ""
}

func (x *ConfigureTopicSchemaRequest) GetValidationPolicy() string {
	if x != nil {
		return x.ValidationPolicy
	}
	return ""
}

func (x *ConfigureTopicSchemaRequest) GetEnablePayloadValidation() bool {
	if x != nil {
		return x.EnablePayloadValidation
	}
	return false
}

type ConfigureTopicSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureTopicSchemaResponse) Reset() {
	*x = ConfigureTopicSchemaResponse{}
	mi := &file_SchemaRegistry_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureTopicSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureTopicSchemaResponse) ProtoMessage() {}

func (x *ConfigureTopicSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_SchemaRegistry_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureTopicSchemaResponse.ProtoReflect.Descriptor instead.
func (*ConfigureTopicSchemaResponse) Descriptor() ([]byte, []int) {
	return file_SchemaRegistry_proto_rawDescGZIP(), []int{15}
}

func (x *ConfigureTopicSchemaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigureTopicSchemaResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request to update validation policy (admin-only)
type UpdateTopicValidationPolicyRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	TopicName               string                 `protobuf:"bytes,1,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	ValidationPolicy        string                 `protobuf:"bytes,2,opt,name=validation_policy,json=validationPolicy,proto3" json:"validation_policy,omitempty"` // "none", "warn", or "enforce"
	EnablePayloadValidation bool                   `protobuf:"varint,3,opt,name=enable_payload_validation,json=enablePayloadValidation,proto3" json:"enable_payload_validation,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *UpdateTopicValidationPolicyRequest) Reset() {
	*x = UpdateTopicValidationPolicyRequest{}
	mi := &file_SchemaRegistry_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTopicValidationPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTopicValidationPolicyRequest) ProtoMessage() {}

func (x *UpdateTopicValidationPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_SchemaRegistry_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTopicValidationPolicyRequest.ProtoReflect.Descriptor instead.
func (*UpdateTopicValidationPolicyRequest) Descriptor() ([]byte, []int) {
	return file_SchemaRegistry_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateTopicValidationPolicyRequest) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *UpdateTopicValidationPolicyRequest) GetValidationPolicy() string {
	if x != nil {
		return x.ValidationPolicy
	}
	return ""
}

func (x *UpdateTopicValidationPolicyRequest) GetEnablePayloadValidation() bool {
	if x != nil {
		return x.EnablePayloadValidation
	}
	return false
}

type UpdateTopicValidationPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTopicValidationPolicyResponse) Reset() {
	*x = UpdateTopicValidationPolicyResponse{}
	mi := &file_SchemaRegistry_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTopicValidationPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTopicValidationPolicyResponse) ProtoMessage() {}

func (x *UpdateTopicValidationPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_SchemaRegistry_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTopicValidationPolicyResponse.ProtoReflect.Descriptor instead.
func (*UpdateTopicValidationPolicyResponse) Descriptor() ([]byte, []int) {
	return file_SchemaRegistry_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateTopicValidationPolicyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateTopicValidationPolicyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request to get topic schema configuration
type GetTopicSchemaConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicName     string                 `protobuf:"bytes,1,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopicSchemaConfigRequest) Reset() {
	*x = GetTopicSchemaConfigRequest{}
	mi := &file_SchemaRegistry_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopicSchemaConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopicSchemaConfigRequest) ProtoMessage() {}

func (x *GetTopicSchemaConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_SchemaRegistry_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopicSchemaConfigRequest.ProtoReflect.Descriptor instead.
func (*GetTopicSchemaConfigRequest) Descriptor() ([]byte, []int) {
	return file_SchemaRegistry_proto_rawDescGZIP(), []int{18}
}

func (x *GetTopicSchemaConfigRequest) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

type GetTopicSchemaConfigResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	SchemaSubject           string                 `protobuf:"bytes,1,opt,name=schema_subject,json=schemaSubject,proto3" json:"schema_subject,omitempty"`                                  // Schema subject assigned to topic
	ValidationPolicy        string                 `protobuf:"bytes,2,opt,name=validation_policy,json=validationPolicy,proto3" json:"validation_policy,omitempty"`                         // Current validation policy
	EnablePayloadValidation bool                   `protobuf:"varint,3,opt,name=enable_payload_validation,json=enablePayloadValidation,proto3" json:"enable_payload_validation,omitempty"` // Whether payload validation is enabled
	SchemaId                uint64                 `protobuf:"varint,4,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`                                                // Cached schema_id for the subject
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GetTopicSchemaConfigResponse) Reset() {
	*x = GetTopicSchemaConfigResponse{}
	mi := &file_SchemaRegistry_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopicSchemaConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopicSchemaConfigResponse) ProtoMessage() {}

func (x *GetTopicSchemaConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_SchemaRegistry_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopicSchemaConfigResponse.ProtoReflect.Descriptor instead.
func (*GetTopicSchemaConfigResponse) Descriptor() ([]byte, []int) {
	return file_SchemaRegistry_proto_rawDescGZIP(), []int{19}
}

func (x *GetTopicSchemaConfigResponse) GetSchemaSubject() string {
	if x != nil {
		return x.SchemaSubject
	}
	return ""
}

func (x *GetTopicSchemaConfigResponse) GetValidationPolicy() string {
	if x != nil {
		return x.ValidationPolicy
	}
	return ""
}

func (x *GetTopicSchemaConfigResponse) GetEnablePayloadValidation() bool {
	if x != nil {
		return x.EnablePayloadValidation
	}
	return false
}

func (x *GetTopicSchemaConfigResponse) GetSchemaId() uint64 {
	if x != nil {
		return x.SchemaId
	}
	return 0
}

var File_SchemaRegistry_proto protoreflect.FileDescriptor

const file_SchemaRegistry_proto_rawDesc = "" +
	"\n" +
	"\x14SchemaRegistry.proto\x12\rdanube_schema\"\xd4\x01\n" +
	"\x15RegisterSchemaRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1f\n" +
	"\vschema_type\x18\x02 \x01(\tR\n" +
	"schemaType\x12+\n" +
	"\x11schema_definition\x18\x03 \x01(\fR\x10schemaDefinition\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\tR\tcreatedBy\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\"\x97\x01\n" +
	"\x16RegisterSchemaResponse\x12\x1b\n" +
	"\tschema_id\x18\x01 \x01(\x04R\bschemaId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x12$\n" +
	"\x0eis_new_version\x18\x03 \x01(\bR\fisNewVersion\x12 \n" +
	"\vfingerprint\x18\x04 \x01(\tR\vfingerprint\"Z\n" +
	"\x10GetSchemaRequest\x12\x1b\n" +
	"\tschema_id\x18\x01 \x01(\x04R\bschemaId\x12\x1d\n" +
	"\aversion\x18\x02 \x01(\rH\x00R\aversion\x88\x01\x01B\n" +
	"\n" +
	"\b_version\"\xf7\x02\n" +
	"\x11GetSchemaResponse\x12\x1b\n" +
	"\tschema_id\x18\x01 \x01(\x04R\bschemaId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x1f\n" +
	"\vschema_type\x18\x04 \x01(\tR\n" +
	"schemaType\x12+\n" +
	"\x11schema_definition\x18\x05 \x01(\fR\x10schemaDefinition\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x04R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\b \x01(\tR\tcreatedBy\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\x12 \n" +
	"\vfingerprint\x18\n" +
	" \x01(\tR\vfingerprint\x12-\n" +
	"\x12compatibility_mode\x18\v \x01(\tR\x11compatibilityMode\"2\n" +
	"\x16GetLatestSchemaRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\"/\n" +
	"\x13ListVersionsRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\"T\n" +
	"\x14ListVersionsResponse\x12<\n" +
	"\bversions\x18\x01 \x03(\v2 .danube_schema.SchemaVersionInfoR\bversions\"\xcc\x01\n" +
	"\x11SchemaVersionInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x04R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\x03 \x01(\tR\tcreatedBy\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12 \n" +
	"\vfingerprint\x18\x05 \x01(\tR\vfingerprint\x12\x1b\n" +
	"\tschema_id\x18\x06 \x01(\x04R\bschemaId\"\xd5\x01\n" +
	"\x19CheckCompatibilityRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x122\n" +
	"\x15new_schema_definition\x18\x02 \x01(\fR\x13newSchemaDefinition\x12\x1f\n" +
	"\vschema_type\x18\x03 \x01(\tR\n" +
	"schemaType\x122\n" +
	"\x12compatibility_mode\x18\x04 \x01(\tH\x00R\x11compatibilityMode\x88\x01\x01B\x15\n" +
	"\x13_compatibility_mode\"Y\n" +
	"\x1aCheckCompatibilityResponse\x12#\n" +
	"\ris_compatible\x18\x01 \x01(\bR\fisCompatible\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors\"P\n" +
	"\x1aDeleteSchemaVersionRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\"Q\n" +
	"\x1bDeleteSchemaVersionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"f\n" +
	"\x1bSetCompatibilityModeRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12-\n" +
	"\x12compatibility_mode\x18\x02 \x01(\tR\x11compatibilityMode\"R\n" +
	"\x1cSetCompatibilityModeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xcc\x01\n" +
	"\x1bConfigureTopicSchemaRequest\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x01 \x01(\tR\ttopicName\x12%\n" +
	"\x0eschema_subject\x18\x02 \x01(\tR\rschemaSubject\x12+\n" +
	"\x11validation_policy\x18\x03 \x01(\tR\x10validationPolicy\x12:\n" +
	"\x19enable_payload_validation\x18\x04 \x01(\bR\x17enablePayloadValidation\"R\n" +
	"\x1cConfigureTopicSchemaResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xac\x01\n" +
	"\"UpdateTopicValidationPolicyRequest\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x01 \x01(\tR\ttopicName\x12+\n" +
	"\x11validation_policy\x18\x02 \x01(\tR\x10validationPolicy\x12:\n" +
	"\x19enable_payload_validation\x18\x03 \x01(\bR\x17enablePayloadValidation\"Y\n" +
	"#UpdateTopicValidationPolicyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"<\n" +
	"\x1bGetTopicSchemaConfigRequest\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x01 \x01(\tR\ttopicName\"\xcb\x01\n" +
	"\x1cGetTopicSchemaConfigResponse\x12%\n" +
	"\x0eschema_subject\x18\x01 \x01(\tR\rschemaSubject\x12+\n" +
	"\x11validation_policy\x18\x02 \x01(\tR\x10validationPolicy\x12:\n" +
	"\x19enable_payload_validation\x18\x03 \x01(\bR\x17enablePayloadValidation\x12\x1b\n" +
	"\tschema_id\x18\x04 \x01(\x04R\bschemaId2\xa7\b\n" +
	"\x0eSchemaRegistry\x12]\n" +
	"\x0eRegisterSchema\x12$.danube_schema.RegisterSchemaRequest\x1a%.danube_schema.RegisterSchemaResponse\x12N\n" +
	"\tGetSchema\x12\x1f.danube_schema.GetSchemaRequest\x1a .danube_schema.GetSchemaResponse\x12Z\n" +
	"\x0fGetLatestSchema\x12%.danube_schema.GetLatestSchemaRequest\x1a .danube_schema.GetSchemaResponse\x12W\n" +
	"\fListVersions\x12\".danube_schema.ListVersionsRequest\x1a#.danube_schema.ListVersionsResponse\x12i\n" +
	"\x12CheckCompatibility\x12(.danube_schema.CheckCompatibilityRequest\x1a).danube_schema.CheckCompatibilityResponse\x12l\n" +
	"\x13DeleteSchemaVersion\x12).danube_schema.DeleteSchemaVersionRequest\x1a*.danube_schema.DeleteSchemaVersionResponse\x12o\n" +
	"\x14SetCompatibilityMode\x12*.danube_schema.SetCompatibilityModeRequest\x1a+.danube_schema.SetCompatibilityModeResponse\x12o\n" +
	"\x14ConfigureTopicSchema\x12*.danube_schema.ConfigureTopicSchemaRequest\x1a+.danube_schema.ConfigureTopicSchemaResponse\x12\x84\x01\n" +
	"\x1bUpdateTopicValidationPolicy\x121.danube_schema.UpdateTopicValidationPolicyRequest\x1a2.danube_schema.UpdateTopicValidationPolicyResponse\x12o\n" +
	"\x14GetTopicSchemaConfig\x12*.danube_schema.GetTopicSchemaConfigRequest\x1a+.danube_schema.GetTopicSchemaConfigResponseB-Z+github.com/danube-messaging/danube-go/protob\x06proto3"

var (
	file_SchemaRegistry_proto_rawDescOnce sync.Once
	file_SchemaRegistry_proto_rawDescData []byte
)

func file_SchemaRegistry_proto_rawDescGZIP() []byte {
	file_SchemaRegistry_proto_rawDescOnce.Do(func() {
		file_SchemaRegistry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SchemaRegistry_proto_rawDesc), len(file_SchemaRegistry_proto_rawDesc)))
	})
	return file_SchemaRegistry_proto_rawDescData
}

var file_SchemaRegistry_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_SchemaRegistry_proto_goTypes = []any{
	(*RegisterSchemaRequest)(nil),               // 0: danube_schema.RegisterSchemaRequest
	(*RegisterSchemaResponse)(nil),              // 1: danube_schema.RegisterSchemaResponse
	(*GetSchemaRequest)(nil),                    // 2: danube_schema.GetSchemaRequest
	(*GetSchemaResponse)(nil),                   // 3: danube_schema.GetSchemaResponse
	(*GetLatestSchemaRequest)(nil),              // 4: danube_schema.GetLatestSchemaRequest
	(*ListVersionsRequest)(nil),                 // 5: danube_schema.ListVersionsRequest
	(*ListVersionsResponse)(nil),                // 6: danube_schema.ListVersionsResponse
	(*SchemaVersionInfo)(nil),                   // 7: danube_schema.SchemaVersionInfo
	(*CheckCompatibilityRequest)(nil),           // 8: danube_schema.CheckCompatibilityRequest
	(*CheckCompatibilityResponse)(nil),          // 9: danube_schema.CheckCompatibilityResponse
	(*DeleteSchemaVersionRequest)(nil),          // 10: danube_schema.DeleteSchemaVersionRequest
	(*DeleteSchemaVersionResponse)(nil),         // 11: danube_schema.DeleteSchemaVersionResponse
	(*SetCompatibilityModeRequest)(nil),         // 12: danube_schema.SetCompatibilityModeRequest
	(*SetCompatibilityModeResponse)(nil),        // 13: danube_schema.SetCompatibilityModeResponse
	(*ConfigureTopicSchemaRequest)(nil),         // 14: danube_schema.ConfigureTopicSchemaRequest
	(*ConfigureTopicSchemaResponse)(nil),        // 15: danube_schema.ConfigureTopicSchemaResponse
	(*UpdateTopicValidationPolicyRequest)(nil),  // 16: danube_schema.UpdateTopicValidationPolicyRequest
	(*UpdateTopicValidationPolicyResponse)(nil), // 17: danube_schema.UpdateTopicValidationPolicyResponse
	(*GetTopicSchemaConfigRequest)(nil),         // 18: danube_schema.GetTopicSchemaConfigRequest
	(*GetTopicSchemaConfigResponse)(nil),        // 19: danube_schema.GetTopicSchemaConfigResponse
}
var file_SchemaRegistry_proto_depIdxs = []int32{
	7,  // 0: danube_schema.ListVersionsResponse.versions:type_name -> danube_schema.SchemaVersionInfo
	0,  // 1: danube_schema.SchemaRegistry.RegisterSchema:input_type -> danube_schema.RegisterSchemaRequest
	2,  // 2: danube_schema.SchemaRegistry.GetSchema:input_type -> danube_schema.GetSchemaRequest
	4,  // 3: danube_schema.SchemaRegistry.GetLatestSchema:input_type -> danube_schema.GetLatestSchemaRequest
	5,  // 4: danube_schema.SchemaRegistry.ListVersions:input_type -> danube_schema.ListVersionsRequest
	8,  // 5: danube_schema.SchemaRegistry.CheckCompatibility:input_type -> danube_schema.CheckCompatibilityRequest
	10, // 6: danube_schema.SchemaRegistry.DeleteSchemaVersion:input_type -> danube_schema.DeleteSchemaVersionRequest
	12, // 7: danube_schema.SchemaRegistry.SetCompatibilityMode:input_type -> danube_schema.SetCompatibilityModeRequest
	14, // 8: danube_schema.SchemaRegistry.ConfigureTopicSchema:input_type -> danube_schema.ConfigureTopicSchemaRequest
	16, // 9: danube_schema.SchemaRegistry.UpdateTopicValidationPolicy:input_type -> danube_schema.UpdateTopicValidationPolicyRequest
	18, // 10: danube_schema.SchemaRegistry.GetTopicSchemaConfig:input_type -> danube_schema.GetTopicSchemaConfigRequest
	1,  // 11: danube_schema.SchemaRegistry.RegisterSchema:output_type -> danube_schema.RegisterSchemaResponse
	3,  // 12: danube_schema.SchemaRegistry.GetSchema:output_type -> danube_schema.GetSchemaResponse
	3,  // 13: danube_schema.SchemaRegistry.GetLatestSchema:output_type -> danube_schema.GetSchemaResponse
	6,  // 14: danube_schema.SchemaRegistry.ListVersions:output_type -> danube_schema.ListVersionsResponse
	9,  // 15: danube_schema.SchemaRegistry.CheckCompatibility:output_type -> danube_schema.CheckCompatibilityResponse
	11, // 16: danube_schema.SchemaRegistry.DeleteSchemaVersion:output_type -> danube_schema.DeleteSchemaVersionResponse
	13, // 17: danube_schema.SchemaRegistry.SetCompatibilityMode:output_type -> danube_schema.SetCompatibilityModeResponse
	15, // 18: danube_schema.SchemaRegistry.ConfigureTopicSchema:output_type -> danube_schema.ConfigureTopicSchemaResponse
	17, // 19: danube_schema.SchemaRegistry.UpdateTopicValidationPolicy:output_type -> danube_schema.UpdateTopicValidationPolicyResponse
	19, // 20: danube_schema.SchemaRegistry.GetTopicSchemaConfig:output_type -> danube_schema.GetTopicSchemaConfigResponse
	11, // [11:21] is the sub-list for method output_type
	1,  // [1:11] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_SchemaRegistry_proto_init() }
func file_SchemaRegistry_proto_init() {
	if File_SchemaRegistry_proto != nil {
		return
	}
	file_SchemaRegistry_proto_msgTypes[2].OneofWrappers = []any{}
	file_SchemaRegistry_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SchemaRegistry_proto_rawDesc), len(file_SchemaRegistry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_SchemaRegistry_proto_goTypes,
		DependencyIndexes: file_SchemaRegistry_proto_depIdxs,
		MessageInfos:      file_SchemaRegistry_proto_msgTypes,
	}.Build()
	File_SchemaRegistry_proto = out.File
	file_SchemaRegistry_proto_goTypes = nil
	file_SchemaRegistry_proto_depIdxs = nil
}
